In [ ]:
settings = {
    ### Encoding layer ### ->for input x
    "enc_pop": 1,
    "beta_enc": 0.9,   # REMEMBER: the range of values is [0, 1]
    "thr_enc": 1,

    ### slstm cell ###
    # Population encoding size for each gate
    "enc_pop_input": 1,
    "enc_pop_gate": 1,
    "enc_pop_forget": 1,
    "enc_pop_output": 1,

    # beta and threshold for neurons pop
    "beta_forget": 0.9,
    "thr_forget": 1,
    "beta_input": 0.9,
    "thr_input": 1,
    "beta_gate": 0.9,
    "thr_gate": 1,
    "beta_output": 0.9,
    "thr_output": 1,
    "beta_hidden": 0.9,
    "thr_hidden": 1,

    ### Output layer #####
    "beta_out": 0.9 ,   # REMEMBER: the range of values is [0, 1]
    "thr_out": 1,
    ######################
    "nb_epochs": 50,
    "lr": 5e-3,
    "batch_size": 128,
}

In [22]:
import torch

batch_size = 128
enc_pop = 32
hidden_size = 16

# Crea un tensore con valori casuali
tensor = torch.randn(batch_size, enc_pop)
tensor.size()

torch.Size([128, 32])

In [12]:
torch.mean(tensor, dim=0).size()

torch.Size([32])

In [18]:
torch.mean(tensor, dim=1).unsqueeze(dim=1).size()

torch.Size([128, 1])

In [20]:
output = torch.mean(tensor, dim=1).unsqueeze(dim=1)

In [29]:
candidate = torch.tanh(output)
candidate.size()

torch.Size([128, 1])

In [24]:
percentages = torch.sigmoid(output)
percentages.size()

torch.Size([128, 1])

In [26]:
syn = torch.ones(batch_size, hidden_size)
syn.size()

torch.Size([128, 16])

In [27]:
new_syn = syn*percentages
new_syn.size()

torch.Size([128, 16])

In [28]:
new_syn[0]

tensor([0.4734, 0.4734, 0.4734, 0.4734, 0.4734, 0.4734, 0.4734, 0.4734, 0.4734,
        0.4734, 0.4734, 0.4734, 0.4734, 0.4734, 0.4734, 0.4734])

In [30]:
new_cur = percentages*candidate
new_cur.size()

torch.Size([128, 1])

In [33]:
new_syn[0]+new_cur[0]
new_syn+new_cur

tensor([0.4233, 0.4233, 0.4233, 0.4233, 0.4233, 0.4233, 0.4233, 0.4233, 0.4233,
        0.4233, 0.4233, 0.4233, 0.4233, 0.4233, 0.4233, 0.4233])

In [32]:
new_syn+new_cur

tensor([[0.4233, 0.4233, 0.4233,  ..., 0.4233, 0.4233, 0.4233],
        [0.5862, 0.5862, 0.5862,  ..., 0.5862, 0.5862, 0.5862],
        [0.5411, 0.5411, 0.5411,  ..., 0.5411, 0.5411, 0.5411],
        ...,
        [0.6552, 0.6552, 0.6552,  ..., 0.6552, 0.6552, 0.6552],
        [0.5488, 0.5488, 0.5488,  ..., 0.5488, 0.5488, 0.5488],
        [0.6900, 0.6900, 0.6900,  ..., 0.6900, 0.6900, 0.6900]])